using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace OpenRA.SourceGenerators.Sync
{
	// https://andrewlock.net/exploring-dotnet-6-part-9-source-generator-updates-incremental-generators/
	[Generator]
	public class SyncHashCodeIncrementalSouceGenerator : IIncrementalGenerator
	{
		public void Initialize(IncrementalGeneratorInitializationContext context)
		{
			var classDeclarationsProvider = context.SyntaxProvider
				.CreateSyntaxProvider(
					predicate: static (syntaxNode, _) => SourceGeneratorHelpers.IsPartialClass(syntaxNode),
					transform: static (generatorContext, _) => GetClassDeclarationSymbol(generatorContext))
				.Where(x => x != null)
				.Collect();

			var compilationAndClasses = context.CompilationProvider.Combine(classDeclarationsProvider);

			context.RegisterSourceOutput(compilationAndClasses,
				static (context, source) => GenerateCode(source.Left, source.Right, context));
		}

		static ClassDeclarationSyntax GetClassDeclarationSymbol(GeneratorSyntaxContext context)
		{
			if (context.SemanticModel.GetDeclaredSymbol(context.Node) is INamedTypeSymbol classSymbol && classSymbol.ImplementsISync())
				return context.Node as ClassDeclarationSyntax;

			return null;
		}

		static void GenerateCode(Compilation compilation, ImmutableArray<ClassDeclarationSyntax> classes, SourceProductionContext context)
		{
			// Nothing to do yet.
			if (classes.IsDefaultOrEmpty)
				return;

			var distinctClasses = classes.Distinct();
			foreach (var classDeclaration in distinctClasses)
			{
				var a = 3;
				var semanticModel = context..GetSemanticModel(classDeclaration.SyntaxTree);
			}
		}

		static (string FileName, string Content) GenerateClass(NameSyntax namespaceName, string className, IEnumerable<string> syncMembersAsHashCodeStrings, bool isSealed, bool syncsTargets)
		{
			return ($"{namespaceName}.{className}.g.cs",
				$@"// <auto-generated/>
{(syncsTargets ? "using OpenRA.Traits;\n" : string.Empty)}
namespace {namespaceName}
{{
	// Explicitly implement the interface again to avoid issues if it is inherited.
	{(isSealed ? "sealed" : "public")} partial class {className} : {SyncHelpers.SyncInterfaceName}
	{{
		int ISync.GetSyncHash()
		{{
			return {string.Join(" ^ ", syncMembersAsHashCodeStrings)};
		}}{(syncsTargets ? $"\n{SyncHelpers.GetTargetSyncHashMethod()}" : string.Empty)}
	}}
}}");
		}
	}
}
